cacheFolder: ./.yarn/cache

checksumBehavior: throw

compressionLevel: mixed

defaultSemverRangePrefix: ''

deferredVersionFolder: ./.yarn/versions

enableConstraintsChecks: true

enableGlobalCache: false

enableImmutableCache: false

enableOfflineMode: false

enableTelemetry: true

enableTransparentWorkspaces: true

injectEnvironmentFiles:
    - .env?

logFilters:
    - level: error

nmHoistingLimits: none

nodeLinker: pnp

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpMode: strict

preferInteractive: true

preferReuse: true

progressBarStyle: patrick

telemetryUserId: '@molitio/web-engine'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
