cacheFolder: ./.yarn/cache

checksumBehavior: throw

compressionLevel: mixed

defaultSemverRangePrefix: ''

deferredVersionFolder: ./.yarn/versions

enableConstraintsChecks: true

enableGlobalCache: false

enableOfflineMode: false

enableImmutableCache: false

enableTelemetry: true

enableTransparentWorkspaces: true

injectEnvironmentFiles:
    - .env?

logFilters:
    - level: info

nmHoistingLimits: workspaces

nodeLinker: pnp

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpMode: strict

preferInteractive: true

preferReuse: true

progressBarStyle: patrick

telemetryUserId: '@molitio/web-engine'
