preferReuse: true
enableTelemetry: true
preferInteractive: true
enableInlnieHunks: true
enableMessageName: true
pnpEnableInlining: true
pnpEnableEsmLoader: true
enableGlobalCache: false
enableImmutableCache: false
preferUnpluggedPackages: true
enableTransparentWorkspaces: true
pnpMode: strict
nodeLinker: pnp
compressionLevel: mixed
checksumBehavior: throw
cacheFolder: ./.yarn/cache
defaultSemverRangePrefix: ''
nmHoistingLimits: 'workspaces'
progressBarStyle: 'patrick'
telemetryUserId: '@molitio/web-engine'
deferredVersionFolder: ./.yarn/versions
yarnPath: .yarn/releases/yarn-4.1.1.cjs
injectEnvironmentFiles:
    - '.env'
logFilters: [{ level: info }]
