apiVersion: v1
kind: ConfigMap
metadata:
    name: resource-hub-ui-config
    namespace: prod
    labels:
        app: resource-hub-ui
data:
    NODE_ENV: production
    API_URL: https://api.example.com
