version: '3.8'
services:
    resource-engine-mongodb:
        image: mongo:5.0.14
        container_name: resource-engine-mongodb
        restart: always
        expose:
            - '27017'
        ports:
            - 27017:27017
        volumes:
            - './resource-engine-mongodb-volume:/resource-enginer-mongodb-volume/db'
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
