apiVersion: apps/v1
kind: Deployment
metadata:
    name: sleeping-dragon-ui
    namespace: dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sleeping-dragon-ui
    template:
        metadata:
            labels:
                app: sleeping-dragon-ui
        spec:
            containers:
                - name: sleeping-dragon-ui
                  image: sleeping-dragon-ui:dev
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                            name: resource-hub-ui-config
                  resources:
                      requests:
                          cpu: '100m'
                          memory: '256Mi'
                      limits:
                          cpu: '500m'
                          memory: '512Mi'
                  volumeMounts:
                      - name: yarn-cache
                        mountPath: /.yarn/cache
            volumes:
                - name: yarn-cache
                  emptyDir: {}
