apiVersion: v1
kind: Service
metadata:
    name: sleeping-dragon-ui-service
spec:
    type: NodePort
    selector:
        app: sleeping-dragon-ui
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30080
