name: Deploy

on:
  workflow_call:
    
env:
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    name: Vercel
    steps:
      - uses: actions/checkout@v3 
      - name: Download UI Core
        uses: actions/download-artifact@v4.1.7
        with:
          name: mwe-ui-core
          path: packages-ui/ui-core/dist
      - run: |
          yarn workspace @molitio/john-glenn unplug next
          yarn workspace @molitio/john-glenn vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
          yarn workspace @molitio/john-glenn build
          yarn workspace @molitio/john-glenn vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
