name: vercel pull request preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
  workflow_dispatch:
    
jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
##    url: ${{ steps.deploy.outputs.url }}
    steps:
    - uses: actions/checkout@v4
    - name: Enable Corepack
      run: corepack enable
    - name: Set Node version to 4.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Build Project
      run: yarn build
    ##  - run: yarn test

    ##  - run: yarn vercel ../packages/john-glenn pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
    ##  - run: yarn vercel ../packages/john-glenn build --token=${{ secrets.VERCEL_TOKEN }}
    ##  - id: deploy
    ##    run: echo "::set-output name=url::$(yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
