apiVersion: v1
kind: ConfigMap
metadata:
    name: resource-hub-ui-config
    namespace: staging
    labels:
        app: resource-hub-ui
data:
    NODE_ENV: staging
    API_URL: http://staging-api:3000
